name: Docker Image

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/workflows/**'
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  build:
    uses: mac-lucky/actions-shared-workflows/.github/workflows/docker-cicd-reusable.yml@master
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    with:
      app_name: "derper"
      dockerhub_image: "maclucky/derper"
      ghcr_image: "ghcr.io/mac-lucky/derper"
      upstream_repo: "tailscale/tailscale"
      version_strip_prefix: ""
      build_arg_name: "DERP_VERSION"
      enable_version_check: true
      enable_schedule_build: true
      enable_security_scan: true
      platforms: "linux/amd64,linux/arm64"